name: Pipeline (build, test:unit, deploy:aws, test:integration)

on:
  push:
    branches: [ "mainline" ]
  pull_request:
    branches: [ "mainline" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout out code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install AWS CDK
      run: npm i -g aws-cdk

    - name: Build/Transpile the code
      run: npm run build:ts

    - name: Run unit tests
      run: npm run test:unit

    - name: Synthesize CDK application
      run: npm run build:cdk

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy CDK
      run: npm run cdk deploy GitHubActionsAwsAuthStackId GraphqlStackId --verbose
