name: Deploy Trigger

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy_dns:
    strategy:
      fail-fast: false
      matrix:
        region: [af-south-1]
    uses: ./.github/workflows/deploy-dns.yaml
    with:
      region: ${{ matrix.region }}
    secrets: inherit

  deploy_beta:
    needs: deploy_dns
    strategy:
      fail-fast: false
      matrix:
        region: [af-south-1]
    uses: ./.github/workflows/deploy.yaml
    with:
      stage: Beta
      region: ${{ matrix.region }}
    secrets: inherit
