name: Pipeline (PR validation + deploy)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

env:
  STAGE: Beta

jobs:
  pr-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run API lint
      run: |
        npm run lint -w @ntlango/api

    - name: Build API TypeScript artifacts
      run: |
        npm run build:ts -w @ntlango/api

    - name: Run API unit tests
      run: |
        npm run test:unit -w @ntlango/api

    - name: Run Webapp lint
      run: npm run lint -w @ntlango/webapp

    # TODO make the webapp build work in PRs
    # - name: Build webapp against running API
    #   run: |
    #     export NEXT_PUBLIC_GRAPHQL_URL=$GRAPHQL_URL

    #     npm run dev -w @ntlango/api

    #     npm run codegen -w @ntlango/webapp
    #     npm run build:ts -w @ntlango/webapp
    #     npm run build:next -w @ntlango/webapp

  api-deploy:
    if: github.event_name == 'pull_request' # TODO change to 'push' for production deploys
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    outputs:
      graphql-url: ${{ steps.get-endpoint.outputs.graphql-url }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install AWS CDK
      run: npm i -g aws-cdk

    - name: Transpile Commons
      run: npm run build:ts -w @ntlango/commons

    - name: Transpile API
      run: npm run build:ts -w @ntlango/api

    - name: Synthesize CDK application
      run: npm run build:cdk -w @ntlango/cdk

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy CDK
      run: npm run cdk -w @ntlango/cdk -- deploy '*'

    - name: Get API Gateway endpoint
      id: get-endpoint
      run: |
        ENDPOINT=$(aws cloudformation describe-stacks --stack-name GraphQLStack --query "Stacks[0].Outputs[?OutputKey=='apiPath'].OutputValue" --output text)
        echo "GRAPHQL_URL=$ENDPOINT" >> $GITHUB_ENV
        echo "graphql-url=$ENDPOINT" >> $GITHUB_OUTPUT

    # TODO enable integration tests
    # - name: Run integration tests
    #   env:
    #     STAGE: ${{ vars.STAGE }}
    #     NTLANGO_SECRET_ARN: ${{ vars.STAGE }}/ntlango/graphql-api
    #     GRAPHQL_URL: ${{ steps.get-endpoint.outputs.graphql-url }}
    #   run: |
    #     echo "The graphql url is ${{ env.GRAPHQL_URL }}"
    #     npm run test:integration -w @ntlango/api

  # webapp-deploy:
  #   if: github.event_name == 'push'
  #   needs: api-deploy
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [24.x]
  #   env:
  #     NEXT_PUBLIC_GRAPHQL_URL: ${{ needs.api-deploy.outputs.graphql-url }}
  #     NEXT_PUBLIC_JWT_SECRET: secret # TODO Placeholder, replace with secure method in production
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Setup Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'

  #   - name: Install dependencies
  #     run: npm ci

  #   - name: Generate GraphQL types
  #     run: npm run codegen -w @ntlango/webapp

  #   - name: Transpile Webapp
  #     run: npm run build:ts -w @ntlango/webapp

  #   - name: Run Next.js build
  #     run: npm run build:next -w @ntlango/webapp
